### ISSUE TITLE
How to include js file from assets 

### ISSUE THREAD

**Issue by baggiaraj** [jualoppaz/single-spa-angular-app#10]
I have an angular project. I have used a third-party module which is RappidJS.  This is having a few js files. before single spa, I was including inside angular.json under scripts section. now I can't have scripts inside it so where to include. can you please direct me

**Comment by jualoppaz** [comment]
Hi @baggiaraj and sorry for the delay!

I am not a very expert of recent angular versions, but I remember from this repo start that I had to configure the different architect steps with the @angular-builders/custom-webpack builder for single-spa as official doc mentions.

It's possible that this dependency is well designed for working with webpack or you must include your custom scripts in other place. If you want to use any other package builder I recommend you refering to the official github repo for **single-spa angular** apps: https://github.com/single-spa/single-spa-angular/issues 

Sorry for cannot help you more.
